/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Box {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Box(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Box obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Box(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Box() {
    this(ilwisobjectsJNI.new_Box__SWIG_0(), true);
  }

  public Box(String envelope) {
    this(ilwisobjectsJNI.new_Box__SWIG_1(envelope), true);
  }

  public Box(Pixel min, Pixel max) {
    this(ilwisobjectsJNI.new_Box__SWIG_2(Pixel.getCPtr(min), min, Pixel.getCPtr(max), max), true);
  }

  public Box(Size size) {
    this(ilwisobjectsJNI.new_Box__SWIG_3(Size.getCPtr(size), size), true);
  }

  public Pixel minCorner() {
    return new Pixel(ilwisobjectsJNI.Box_minCorner(swigCPtr, this), true);
  }

  public Pixel maxCorner() {
    return new Pixel(ilwisobjectsJNI.Box_maxCorner(swigCPtr, this), true);
  }

  public Size size() {
    return new Size(ilwisobjectsJNI.Box_size(swigCPtr, this), true);
  }

  public boolean is3D() {
    return ilwisobjectsJNI.Box_is3D(swigCPtr, this);
  }

  public boolean contains(Pixel point) {
    return ilwisobjectsJNI.Box_contains__SWIG_0(swigCPtr, this, Pixel.getCPtr(point), point);
  }

  public boolean contains(Box box) {
    return ilwisobjectsJNI.Box_contains__SWIG_1(swigCPtr, this, Box.getCPtr(box), box);
  }

  public boolean equals(Box other) {
    return ilwisobjectsJNI.Box_equals(swigCPtr, this, Box.getCPtr(other), other);
  }

  public boolean notequal(Box other) {
    return ilwisobjectsJNI.Box_notequal(swigCPtr, this, Box.getCPtr(other), other);
  }

  public String toString() {
    return ilwisobjectsJNI.Box_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.Box_isValid(swigCPtr, this);
  }

}
