/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Catalog extends IObject {
  private long swigCPtr;

  protected Catalog(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.Catalog_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Catalog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Catalog(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Catalog(String url, String filter) {
    this(ilwisobjectsJNI.new_Catalog__SWIG_0(url, filter), true);
  }

  public Catalog(String url) {
    this(ilwisobjectsJNI.new_Catalog__SWIG_1(url), true);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.Catalog_isValid(swigCPtr, this);
  }

  public String toString() {
    return ilwisobjectsJNI.Catalog_toString(swigCPtr, this);
  }

  public java.math.BigInteger ilwisType() {
    return ilwisobjectsJNI.Catalog_ilwisType(swigCPtr, this);
  }

  public vectors items() {
    return new vectors(ilwisobjectsJNI.Catalog_items(swigCPtr, this), true);
  }

  public IObject _getitem(String name) {
    long cPtr = ilwisobjectsJNI.Catalog__getitem(swigCPtr, this, name);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public Catalog toCatalog(IObject obj) {
    long cPtr = ilwisobjectsJNI.Catalog_toCatalog(swigCPtr, this, IObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Catalog(cPtr, false);
  }

}
