/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Color {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Color() {
    this(ilwisobjectsJNI.new_Color__SWIG_0(), true);
  }

  public Color(ColorModel.Value type, SWIGTYPE_p_QVariant obj, String name) {
    this(ilwisobjectsJNI.new_Color__SWIG_1(type.swigValue(), SWIGTYPE_p_QVariant.getCPtr(obj), name), true);
  }

  public Color(ColorModel.Value type, SWIGTYPE_p_QVariant obj) {
    this(ilwisobjectsJNI.new_Color__SWIG_2(type.swigValue(), SWIGTYPE_p_QVariant.getCPtr(obj)), true);
  }

  public Color(String typeStr, SWIGTYPE_p_QVariant obj, String name) {
    this(ilwisobjectsJNI.new_Color__SWIG_3(typeStr, SWIGTYPE_p_QVariant.getCPtr(obj), name), true);
  }

  public Color(String typeStr, SWIGTYPE_p_QVariant obj) {
    this(ilwisobjectsJNI.new_Color__SWIG_4(typeStr, SWIGTYPE_p_QVariant.getCPtr(obj)), true);
  }

  public double getItem(String key) {
    return ilwisobjectsJNI.Color_getItem(swigCPtr, this, key);
  }

  public void setName(String name) {
    ilwisobjectsJNI.Color_setName(swigCPtr, this, name);
  }

  public String getName() {
    return ilwisobjectsJNI.Color_getName(swigCPtr, this);
  }

  public ColorModel.Value getColorModel() {
    return ColorModel.Value.swigToEnum(ilwisobjectsJNI.Color_getColorModel(swigCPtr, this));
  }

  public String toString() {
    return ilwisobjectsJNI.Color_toString(swigCPtr, this);
  }

}
