/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ColorRange extends Range {
  private long swigCPtr;

  protected ColorRange(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ColorRange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColorRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ColorRange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ColorRange() {
    this(ilwisobjectsJNI.new_ColorRange__SWIG_0(), true);
  }

  public ColorRange(java.math.BigInteger tp, ColorModel.Value clrmodel) {
    this(ilwisobjectsJNI.new_ColorRange__SWIG_1(tp, clrmodel.swigValue()), true);
  }

  public ColorModel.Value defaultColorModel() {
    return ColorModel.Value.swigToEnum(ilwisobjectsJNI.ColorRange_defaultColorModel__SWIG_0(swigCPtr, this));
  }

  public void defaultColorModel(ColorModel.Value m) {
    ilwisobjectsJNI.ColorRange_defaultColorModel__SWIG_1(swigCPtr, this, m.swigValue());
  }

  public static Color toColor(java.math.BigInteger clrint, ColorModel.Value clrModel, String name) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_0(clrint, clrModel.swigValue(), name), true);
  }

  public static Color toColor(java.math.BigInteger clrint, ColorModel.Value clrModel) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_1(clrint, clrModel.swigValue()), true);
  }

  public static Color toColor(vectord v, ColorModel.Value colortype, String name) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_2(vectord.getCPtr(v), v, colortype.swigValue(), name), true);
  }

  public static Color toColor(vectord v, ColorModel.Value colortype) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_3(vectord.getCPtr(v), v, colortype.swigValue()), true);
  }

  public static Color toColor(String v, ColorModel.Value colortype, String name) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_4(v, colortype.swigValue(), name), true);
  }

  public static Color toColor(String v, ColorModel.Value colortype) {
    return new Color(ilwisobjectsJNI.ColorRange_toColor__SWIG_5(v, colortype.swigValue()), true);
  }

}
