/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Coordinate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Coordinate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Coordinate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Coordinate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Coordinate(double x, double y) {
    this(ilwisobjectsJNI.new_Coordinate__SWIG_0(x, y), true);
  }

  public Coordinate(double x, double y, double z) {
    this(ilwisobjectsJNI.new_Coordinate__SWIG_1(x, y, z), true);
  }

  public Coordinate(Coordinate crd) {
    this(ilwisobjectsJNI.new_Coordinate__SWIG_2(Coordinate.getCPtr(crd), crd), true);
  }

  public double x() {
    return ilwisobjectsJNI.Coordinate_x(swigCPtr, this);
  }

  public double y() {
    return ilwisobjectsJNI.Coordinate_y(swigCPtr, this);
  }

  public double z() {
    return ilwisobjectsJNI.Coordinate_z(swigCPtr, this);
  }

  public void setX(double v) {
    ilwisobjectsJNI.Coordinate_setX(swigCPtr, this, v);
  }

  public void setY(double v) {
    ilwisobjectsJNI.Coordinate_setY(swigCPtr, this, v);
  }

  public void setZ(double v) {
    ilwisobjectsJNI.Coordinate_setZ(swigCPtr, this, v);
  }

  public boolean is3D() {
    return ilwisobjectsJNI.Coordinate_is3D(swigCPtr, this);
  }

  public Coordinate multiply(double n) {
    long cPtr = ilwisobjectsJNI.Coordinate_multiply(swigCPtr, this, n);
    return (cPtr == 0) ? null : new Coordinate(cPtr, false);
  }

  public Coordinate __itruediv__(double n) {
    long cPtr = ilwisobjectsJNI.Coordinate___itruediv__(swigCPtr, this, n);
    return (cPtr == 0) ? null : new Coordinate(cPtr, false);
  }

  public boolean equal(Coordinate other) {
    return ilwisobjectsJNI.Coordinate_equal(swigCPtr, this, Coordinate.getCPtr(other), other);
  }

  public boolean notequal(Coordinate other) {
    return ilwisobjectsJNI.Coordinate_notequal(swigCPtr, this, Coordinate.getCPtr(other), other);
  }

  public String toString() {
    return ilwisobjectsJNI.Coordinate_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.Coordinate_isValid(swigCPtr, this);
  }

}
