/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class DataDefinition {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_DataDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataDefinition() {
    this(ilwisobjectsJNI.new_DataDefinition__SWIG_0(), true);
  }

  public DataDefinition(Domain dm, Range rng) {
    this(ilwisobjectsJNI.new_DataDefinition__SWIG_1(Domain.getCPtr(dm), dm, Range.getCPtr(rng), rng), true);
  }

  public DataDefinition(Domain dm) {
    this(ilwisobjectsJNI.new_DataDefinition__SWIG_2(Domain.getCPtr(dm), dm), true);
  }

  public DataDefinition(DataDefinition datdef) {
    this(ilwisobjectsJNI.new_DataDefinition__SWIG_3(DataDefinition.getCPtr(datdef), datdef), true);
  }

  public String toString() {
    return ilwisobjectsJNI.DataDefinition_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.DataDefinition_isValid(swigCPtr, this);
  }

  public void range(Range rng) {
    ilwisobjectsJNI.DataDefinition_range__SWIG_0(swigCPtr, this, Range.getCPtr(rng), rng);
  }

  public void domain(Domain dm) {
    ilwisobjectsJNI.DataDefinition_domain__SWIG_0(swigCPtr, this, Domain.getCPtr(dm), dm);
  }

  public boolean isCompatibleWith(DataDefinition datdef) {
    return ilwisobjectsJNI.DataDefinition_isCompatibleWith(swigCPtr, this, DataDefinition.getCPtr(datdef), datdef);
  }

  public DataDefinition merge(DataDefinition datdef1, DataDefinition datdef2) {
    long cPtr = ilwisobjectsJNI.DataDefinition_merge(swigCPtr, this, DataDefinition.getCPtr(datdef1), datdef1, DataDefinition.getCPtr(datdef2), datdef2);
    return (cPtr == 0) ? null : new DataDefinition(cPtr, false);
  }

  public DataDefinition set(DataDefinition datdef) {
    long cPtr = ilwisobjectsJNI.DataDefinition_set(swigCPtr, this, DataDefinition.getCPtr(datdef), datdef);
    return (cPtr == 0) ? null : new DataDefinition(cPtr, false);
  }

  public Range range() {
    long cPtr = ilwisobjectsJNI.DataDefinition_range__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Range(cPtr, false);
  }

  public Domain domain() {
    long cPtr = ilwisobjectsJNI.DataDefinition_domain__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Domain(cPtr, false);
  }

}
