/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class DomainItem extends IObject {
  private long swigCPtr;

  protected DomainItem(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.DomainItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DomainItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_DomainItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DomainItem() {
    this(ilwisobjectsJNI.new_DomainItem__SWIG_0(), true);
  }

  public DomainItem(SWIGTYPE_p_Ilwis__DomainItem ilwItem) {
    this(ilwisobjectsJNI.new_DomainItem__SWIG_1(SWIGTYPE_p_Ilwis__DomainItem.getCPtr(ilwItem)), true);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.DomainItem_isValid(swigCPtr, this);
  }

  public String toString() {
    return ilwisobjectsJNI.DomainItem_toString(swigCPtr, this);
  }

  public java.math.BigInteger ilwisType() {
    return ilwisobjectsJNI.DomainItem_ilwisType(swigCPtr, this);
  }

  public DomainItem clone() {
    long cPtr = ilwisobjectsJNI.DomainItem_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new DomainItem(cPtr, false);
  }

  public void raw(long rw) {
    ilwisobjectsJNI.DomainItem_raw__SWIG_0(swigCPtr, this, rw);
  }

  public long raw() {
    return ilwisobjectsJNI.DomainItem_raw__SWIG_1(swigCPtr, this);
  }

}
