/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Engine {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Engine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Engine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Engine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Engine() {
    this(ilwisobjectsJNI.new_Engine(), true);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4, String c5, String c6, String c7, String c8, String c9) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_0(output_name, operation, c3, c4, c5, c6, c7, c8, c9);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4, String c5, String c6, String c7, String c8) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_1(output_name, operation, c3, c4, c5, c6, c7, c8);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4, String c5, String c6, String c7) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_2(output_name, operation, c3, c4, c5, c6, c7);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4, String c5, String c6) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_3(output_name, operation, c3, c4, c5, c6);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4, String c5) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_4(output_name, operation, c3, c4, c5);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3, String c4) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_5(output_name, operation, c3, c4);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation, String c3) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_6(output_name, operation, c3);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static IObject _do(String output_name, String operation) {
    long cPtr = ilwisobjectsJNI.Engine__do__SWIG_7(output_name, operation);
    return (cPtr == 0) ? null : new IObject(cPtr, false);
  }

  public static void setWorkingCatalog(String location) {
    ilwisobjectsJNI.Engine_setWorkingCatalog(location);
  }

  public static String getLocation() {
    return ilwisobjectsJNI.Engine_getLocation();
  }

  public vectors operations(String filter) {
    return new vectors(ilwisobjectsJNI.Engine_operations__SWIG_0(swigCPtr, this, filter), true);
  }

  public vectors operations() {
    return new vectors(ilwisobjectsJNI.Engine_operations__SWIG_1(swigCPtr, this), true);
  }

  public String operationMetaData(String name) {
    return ilwisobjectsJNI.Engine_operationMetaData(swigCPtr, this, name);
  }

}
