/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ilwisobjects {
  public static boolean _initIlwisObjects(String ilwisDir) {
    return ilwisobjectsJNI._initIlwisObjects(ilwisDir);
  }

  public static void _exitIlwisObjects() {
    ilwisobjectsJNI._exitIlwisObjects();
  }

  public static void disconnectIssueLogger() {
    ilwisobjectsJNI.disconnectIssueLogger();
  }

  public static void connectIssueLogger() {
    ilwisobjectsJNI.connectIssueLogger();
  }

  public static int getCOVERAGEATRIB() {
    return ilwisobjectsJNI.COVERAGEATRIB_get();
  }

  public static double getRUNDEF() {
    return ilwisobjectsJNI.rUNDEF_get();
  }

  public static int getIUNDEF() {
    return ilwisobjectsJNI.iUNDEF_get();
  }

  public static long getI64UNDEF() {
    return ilwisobjectsJNI.i64UNDEF_get();
  }


  public static String getsUNDEF() { return "?"; }
  public static int getshUNDEF() { return 32767; }
  public static float getFlUNDEF() { return (float)1e38; }

}
