/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ilwisobjects {
  public static boolean _initIlwisObjects(String ilwisDir) {
    return ilwisobjectsJNI._initIlwisObjects(ilwisDir);
  }

  public static void _exitIlwisObjects() {
    ilwisobjectsJNI._exitIlwisObjects();
  }

  public static void disconnectIssueLogger() {
    ilwisobjectsJNI.disconnectIssueLogger();
  }

  public static void connectIssueLogger() {
    ilwisobjectsJNI.connectIssueLogger();
  }

}
