/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class IndexedIdentifier extends DomainItem {
  private long swigCPtr;

  protected IndexedIdentifier(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.IndexedIdentifier_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexedIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_IndexedIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IndexedIdentifier() {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_0(), true);
  }

  public IndexedIdentifier(String label, long ind, int cnt) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_1(label, ind, cnt), true);
  }

  public IndexedIdentifier(String label, long ind) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_2(label, ind), true);
  }

  public IndexedIdentifier(String label) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_3(label), true);
  }

  public IndexedIdentifier(SWIGTYPE_p_Ilwis__DomainItem ilwItem) {
    this(ilwisobjectsJNI.new_IndexedIdentifier__SWIG_4(SWIGTYPE_p_Ilwis__DomainItem.getCPtr(ilwItem)), true);
  }

  public String prefix() {
    return ilwisobjectsJNI.IndexedIdentifier_prefix(swigCPtr, this);
  }

  public void setPrefix(String name) {
    ilwisobjectsJNI.IndexedIdentifier_setPrefix(swigCPtr, this, name);
  }

  public boolean equals(IndexedIdentifier item) {
    return ilwisobjectsJNI.IndexedIdentifier_equals(swigCPtr, this, IndexedIdentifier.getCPtr(item), item);
  }

}
