/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Interval extends DomainItem {
  private long swigCPtr;

  protected Interval(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.Interval_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Interval obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Interval(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Interval() {
    this(ilwisobjectsJNI.new_Interval__SWIG_0(), true);
  }

  public Interval(String label, NumericRange nr) {
    this(ilwisobjectsJNI.new_Interval__SWIG_1(label, NumericRange.getCPtr(nr), nr), true);
  }

  public boolean isOrdered() {
    return ilwisobjectsJNI.Interval_isOrdered(swigCPtr, this);
  }

  public NumericRange range() {
    return new NumericRange(ilwisobjectsJNI.Interval_range__SWIG_0(swigCPtr, this), true);
  }

  public void range(NumericRange nr) {
    ilwisobjectsJNI.Interval_range__SWIG_1(swigCPtr, this, NumericRange.getCPtr(nr), nr);
  }

}
