/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class IObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_IObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean __bool__() {
    return ilwisobjectsJNI.IObject___bool__(swigCPtr, this);
  }

  public String __str__() {
    return ilwisobjectsJNI.IObject___str__(swigCPtr, this);
  }

  public java.math.BigInteger ilwisType() {
    return ilwisobjectsJNI.IObject_ilwisType(swigCPtr, this);
  }

}
