/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class IOOptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IOOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IOOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_IOOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IOOptions() {
    this(ilwisobjectsJNI.new_IOOptions__SWIG_0(), true);
  }

  public IOOptions(String key, SWIGTYPE_p_QVariant value) {
    this(ilwisobjectsJNI.new_IOOptions__SWIG_1(key, SWIGTYPE_p_QVariant.getCPtr(value)), true);
  }

  public boolean contains(String option) {
    return ilwisobjectsJNI.IOOptions_contains(swigCPtr, this, option);
  }

  public long size() {
    return ilwisobjectsJNI.IOOptions_size(swigCPtr, this);
  }

  public SWIGTYPE_p_QVariant __getitem__(String option) {
    return new SWIGTYPE_p_QVariant(ilwisobjectsJNI.IOOptions___getitem__(swigCPtr, this, option), true);
  }

  public IOOptions addOption(String key, SWIGTYPE_p_QVariant value) {
    return new IOOptions(ilwisobjectsJNI.IOOptions_addOption(swigCPtr, this, key, SWIGTYPE_p_QVariant.getCPtr(value)), false);
  }

}
