/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class it {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected it(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(it obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_it(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public it() {
    this(ilwisobjectsJNI.new_it(), true);
  }

  public final static class ilwisType {
    public final static it.ilwisType FEATURE = new it.ilwisType("FEATURE", ilwisobjectsJNI.it_FEATURE_get());
    public final static it.ilwisType RASTER = new it.ilwisType("RASTER", ilwisobjectsJNI.it_RASTER_get());
    public final static it.ilwisType COVERAGE = new it.ilwisType("COVERAGE", ilwisobjectsJNI.it_COVERAGE_get());
    public final static it.ilwisType TABLE = new it.ilwisType("TABLE", ilwisobjectsJNI.it_TABLE_get());
    public final static it.ilwisType GEOREF = new it.ilwisType("GEOREF", ilwisobjectsJNI.it_GEOREF_get());
    public final static it.ilwisType COORDSYSTEM = new it.ilwisType("COORDSYSTEM", ilwisobjectsJNI.it_COORDSYSTEM_get());
    public final static it.ilwisType DOMAIN = new it.ilwisType("DOMAIN", ilwisobjectsJNI.it_DOMAIN_get());
    public final static it.ilwisType NUMERICDOMAIN = new it.ilwisType("NUMERICDOMAIN", ilwisobjectsJNI.it_NUMERICDOMAIN_get());
    public final static it.ilwisType ITEMDOMAIN = new it.ilwisType("ITEMDOMAIN", ilwisobjectsJNI.it_ITEMDOMAIN_get());
    public final static it.ilwisType OPERATIONMETADATA = new it.ilwisType("OPERATIONMETADATA", ilwisobjectsJNI.it_OPERATIONMETADATA_get());
    public final static it.ilwisType PROJECTION = new it.ilwisType("PROJECTION", ilwisobjectsJNI.it_PROJECTION_get());
    public final static it.ilwisType ELLIPSOID = new it.ilwisType("ELLIPSOID", ilwisobjectsJNI.it_ELLIPSOID_get());
    public final static it.ilwisType CATALOG = new it.ilwisType("CATALOG", ilwisobjectsJNI.it_CATALOG_get());
    public final static it.ilwisType CONTINUOUSCOLOR = new it.ilwisType("CONTINUOUSCOLOR", ilwisobjectsJNI.it_CONTINUOUSCOLOR_get());
    public final static it.ilwisType PALETTECOLOR = new it.ilwisType("PALETTECOLOR", ilwisobjectsJNI.it_PALETTECOLOR_get());
    public final static it.ilwisType VALUERANGE = new it.ilwisType("VALUERANGE", ilwisobjectsJNI.it_VALUERANGE_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ilwisType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ilwisType.class + " with value " + swigValue);
    }

    private ilwisType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ilwisType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ilwisType(String swigName, ilwisType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ilwisType[] swigValues = { FEATURE, RASTER, COVERAGE, TABLE, GEOREF, COORDSYSTEM, DOMAIN, NUMERICDOMAIN, ITEMDOMAIN, OPERATIONMETADATA, PROJECTION, ELLIPSOID, CATALOG, CONTINUOUSCOLOR, PALETTECOLOR, VALUERANGE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
