/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ItemDomain extends Domain {
  private long swigCPtr;

  protected ItemDomain(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ItemDomain_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ItemDomain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ItemDomain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ItemDomain() {
    this(ilwisobjectsJNI.new_ItemDomain__SWIG_0(), true);
  }

  public ItemDomain(Range rng) {
    this(ilwisobjectsJNI.new_ItemDomain__SWIG_1(Range.getCPtr(rng), rng), true);
  }

  public long count() {
    return ilwisobjectsJNI.ItemDomain_count(swigCPtr, this);
  }

  public void setTheme(String theme) {
    ilwisobjectsJNI.ItemDomain_setTheme(swigCPtr, this, theme);
  }

  public String theme() {
    return ilwisobjectsJNI.ItemDomain_theme(swigCPtr, this);
  }

  public void removeItem(String nme) {
    ilwisobjectsJNI.ItemDomain_removeItem(swigCPtr, this, nme);
  }

  public void range(Range rng) {
    ilwisobjectsJNI.ItemDomain_range(swigCPtr, this, Range.getCPtr(rng), rng);
  }

}
