/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ItemRange extends Range {
  private long swigCPtr;

  protected ItemRange(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ItemRange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ItemRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ItemRange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void add(SWIGTYPE_p_QVariant dItem) {
    ilwisobjectsJNI.ItemRange_add(swigCPtr, this, SWIGTYPE_p_QVariant.getCPtr(dItem));
  }

  public long count() {
    return ilwisobjectsJNI.ItemRange_count(swigCPtr, this);
  }

  public void remove(String name) {
    ilwisobjectsJNI.ItemRange_remove(swigCPtr, this, name);
  }

  public void clear() {
    ilwisobjectsJNI.ItemRange_clear(swigCPtr, this);
  }

}
