/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class mapsd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mapsd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mapsd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_mapsd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public mapsd() {
    this(ilwisobjectsJNI.new_mapsd__SWIG_0(), true);
  }

  public mapsd(mapsd arg0) {
    this(ilwisobjectsJNI.new_mapsd__SWIG_1(mapsd.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return ilwisobjectsJNI.mapsd_size(swigCPtr, this);
  }

  public boolean empty() {
    return ilwisobjectsJNI.mapsd_empty(swigCPtr, this);
  }

  public void clear() {
    ilwisobjectsJNI.mapsd_clear(swigCPtr, this);
  }

  public double get(String key) {
    return ilwisobjectsJNI.mapsd_get(swigCPtr, this, key);
  }

  public void set(String key, double x) {
    ilwisobjectsJNI.mapsd_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    ilwisobjectsJNI.mapsd_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return ilwisobjectsJNI.mapsd_has_key(swigCPtr, this, key);
  }

}
