/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class NamedItemRange extends ItemRange {
  private long swigCPtr;

  protected NamedItemRange(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.NamedItemRange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NamedItemRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_NamedItemRange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NamedItemRange() {
    this(ilwisobjectsJNI.new_NamedItemRange(), true);
  }

  public void add(String item) {
    ilwisobjectsJNI.NamedItemRange_add(swigCPtr, this, item);
  }

  public vectors listAll() {
    return new vectors(ilwisobjectsJNI.NamedItemRange_listAll(swigCPtr, this), true);
  }

  public int gotoIndex(int index, int step) {
    return ilwisobjectsJNI.NamedItemRange_gotoIndex(swigCPtr, this, index, step);
  }

  public NamedItemRange clone() {
    long cPtr = ilwisobjectsJNI.NamedItemRange_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new NamedItemRange(cPtr, false);
  }

}
