/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class NamedIdentifier extends DomainItem {
  private long swigCPtr;

  protected NamedIdentifier(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.NamedIdentifier_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NamedIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_NamedIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NamedIdentifier() {
    this(ilwisobjectsJNI.new_NamedIdentifier__SWIG_0(), true);
  }

  public NamedIdentifier(String name, long rawvalue) {
    this(ilwisobjectsJNI.new_NamedIdentifier__SWIG_1(name, rawvalue), true);
  }

  public NamedIdentifier(String name) {
    this(ilwisobjectsJNI.new_NamedIdentifier__SWIG_2(name), true);
  }

  public NamedIdentifier(SWIGTYPE_p_Ilwis__DomainItem ilwItem) {
    this(ilwisobjectsJNI.new_NamedIdentifier__SWIG_3(SWIGTYPE_p_Ilwis__DomainItem.getCPtr(ilwItem)), true);
  }

  public void setName(String name) {
    ilwisobjectsJNI.NamedIdentifier_setName(swigCPtr, this, name);
  }

  public boolean equals(NamedIdentifier item) {
    return ilwisobjectsJNI.NamedIdentifier_equals(swigCPtr, this, NamedIdentifier.getCPtr(item), item);
  }

}
