/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class NumericDomain extends Domain {
  private long swigCPtr;

  protected NumericDomain(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.NumericDomain_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NumericDomain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_NumericDomain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NumericDomain() {
    this(ilwisobjectsJNI.new_NumericDomain__SWIG_0(), true);
  }

  public NumericDomain(String resource) {
    this(ilwisobjectsJNI.new_NumericDomain__SWIG_1(resource), true);
  }

  public static NumericDomain toNumericDomain(IObject obj) {
    long cPtr = ilwisobjectsJNI.NumericDomain_toNumericDomain(IObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new NumericDomain(cPtr, false);
  }

}
