/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class Pixel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Pixel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pixel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_Pixel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pixel(Pixel pixel) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_0(Pixel.getCPtr(pixel), pixel), true);
  }

  public Pixel(PixelD pixel) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_1(PixelD.getCPtr(pixel), pixel), true);
  }

  public Pixel(int x, int y) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_2(x, y), true);
  }

  public Pixel(int x, int y, int z) {
    this(ilwisobjectsJNI.new_Pixel__SWIG_3(x, y, z), true);
  }

  public int x() {
    return ilwisobjectsJNI.Pixel_x(swigCPtr, this);
  }

  public int y() {
    return ilwisobjectsJNI.Pixel_y(swigCPtr, this);
  }

  public int z() {
    return ilwisobjectsJNI.Pixel_z(swigCPtr, this);
  }

  public void setX(int v) {
    ilwisobjectsJNI.Pixel_setX(swigCPtr, this, v);
  }

  public void setY(int v) {
    ilwisobjectsJNI.Pixel_setY(swigCPtr, this, v);
  }

  public void setZ(int v) {
    ilwisobjectsJNI.Pixel_setZ(swigCPtr, this, v);
  }

  public boolean is3D() {
    return ilwisobjectsJNI.Pixel_is3D(swigCPtr, this);
  }

  public Pixel __itruediv__(int n) {
    long cPtr = ilwisobjectsJNI.Pixel___itruediv__(swigCPtr, this, n);
    return (cPtr == 0) ? null : new Pixel(cPtr, false);
  }

  public String __str__() {
    return ilwisobjectsJNI.Pixel___str__(swigCPtr, this);
  }

  public boolean __bool__() {
    return ilwisobjectsJNI.Pixel___bool__(swigCPtr, this);
  }

}
