/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class PixelD {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PixelD(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PixelD obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_PixelD(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PixelD(Pixel pixel) {
    this(ilwisobjectsJNI.new_PixelD__SWIG_0(Pixel.getCPtr(pixel), pixel), true);
  }

  public PixelD(PixelD pixel) {
    this(ilwisobjectsJNI.new_PixelD__SWIG_1(PixelD.getCPtr(pixel), pixel), true);
  }

  public PixelD(double x, double y) {
    this(ilwisobjectsJNI.new_PixelD__SWIG_2(x, y), true);
  }

  public PixelD(double x, double y, double z) {
    this(ilwisobjectsJNI.new_PixelD__SWIG_3(x, y, z), true);
  }

  public double x() {
    return ilwisobjectsJNI.PixelD_x(swigCPtr, this);
  }

  public double y() {
    return ilwisobjectsJNI.PixelD_y(swigCPtr, this);
  }

  public double z() {
    return ilwisobjectsJNI.PixelD_z(swigCPtr, this);
  }

  public void setX(double v) {
    ilwisobjectsJNI.PixelD_setX(swigCPtr, this, v);
  }

  public void setY(double v) {
    ilwisobjectsJNI.PixelD_setY(swigCPtr, this, v);
  }

  public void setZ(double v) {
    ilwisobjectsJNI.PixelD_setZ(swigCPtr, this, v);
  }

  public boolean is3D() {
    return ilwisobjectsJNI.PixelD_is3D(swigCPtr, this);
  }

  public PixelD multiply(double n) {
    long cPtr = ilwisobjectsJNI.PixelD_multiply(swigCPtr, this, n);
    return (cPtr == 0) ? null : new PixelD(cPtr, false);
  }

  public PixelD divide(double n) {
    long cPtr = ilwisobjectsJNI.PixelD_divide(swigCPtr, this, n);
    return (cPtr == 0) ? null : new PixelD(cPtr, false);
  }

  public boolean equal(PixelD other) {
    return ilwisobjectsJNI.PixelD_equal(swigCPtr, this, PixelD.getCPtr(other), other);
  }

  public boolean notequal(PixelD other) {
    return ilwisobjectsJNI.PixelD_notequal(swigCPtr, this, PixelD.getCPtr(other), other);
  }

  public String toString() {
    return ilwisobjectsJNI.PixelD_toString(swigCPtr, this);
  }

  public boolean isValid() {
    return ilwisobjectsJNI.PixelD_isValid(swigCPtr, this);
  }

}
