/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class SWIGTYPE_p_Ilwis__DomainItem {
  private long swigCPtr;

  protected SWIGTYPE_p_Ilwis__DomainItem(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_Ilwis__DomainItem() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_Ilwis__DomainItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

