/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class TextDomain extends Domain {
  private long swigCPtr;

  protected TextDomain(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.TextDomain_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextDomain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_TextDomain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TextDomain() {
    this(ilwisobjectsJNI.new_TextDomain__SWIG_0(), true);
  }

  public TextDomain(String resource) {
    this(ilwisobjectsJNI.new_TextDomain__SWIG_1(resource), true);
  }

}
