/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ThematicItem extends NamedIdentifier {
  private long swigCPtr;

  protected ThematicItem(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ThematicItem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThematicItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ThematicItem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ThematicItem() {
    this(ilwisobjectsJNI.new_ThematicItem__SWIG_0(), true);
  }

  public ThematicItem(SWIGTYPE_p_Ilwis__DomainItem ilwItem) {
    this(ilwisobjectsJNI.new_ThematicItem__SWIG_1(SWIGTYPE_p_Ilwis__DomainItem.getCPtr(ilwItem)), true);
  }

  public String description() {
    return ilwisobjectsJNI.ThematicItem_description__SWIG_0(swigCPtr, this);
  }

  public void description(String descr) {
    ilwisobjectsJNI.ThematicItem_description__SWIG_1(swigCPtr, this, descr);
  }

  public String code() {
    return ilwisobjectsJNI.ThematicItem_code__SWIG_0(swigCPtr, this);
  }

  public void code(String code) {
    ilwisobjectsJNI.ThematicItem_code__SWIG_1(swigCPtr, this, code);
  }

}
