/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class ThematicRange extends ItemRange {
  private long swigCPtr;

  protected ThematicRange(long cPtr, boolean cMemoryOwn) {
    super(ilwisobjectsJNI.ThematicRange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThematicRange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_ThematicRange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ThematicRange() {
    this(ilwisobjectsJNI.new_ThematicRange(), true);
  }

  public void add(String name, String id, String descr) {
    ilwisobjectsJNI.ThematicRange_add__SWIG_0(swigCPtr, this, name, id, descr);
  }

  public void add(String name, String id) {
    ilwisobjectsJNI.ThematicRange_add__SWIG_1(swigCPtr, this, name, id);
  }

  public void add(String name) {
    ilwisobjectsJNI.ThematicRange_add__SWIG_2(swigCPtr, this, name);
  }

  public vectorvs listAll() {
    return new vectorvs(ilwisobjectsJNI.ThematicRange_listAll(swigCPtr, this), true);
  }

  public ThematicRange clone() {
    long cPtr = ilwisobjectsJNI.ThematicRange_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ThematicRange(cPtr, false);
  }

}
