/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class vectors {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectors(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_vectors(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectors() {
    this(ilwisobjectsJNI.new_vectors__SWIG_0(), true);
  }

  public vectors(long n) {
    this(ilwisobjectsJNI.new_vectors__SWIG_1(n), true);
  }

  public long size() {
    return ilwisobjectsJNI.vectors_size(swigCPtr, this);
  }

  public long capacity() {
    return ilwisobjectsJNI.vectors_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ilwisobjectsJNI.vectors_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ilwisobjectsJNI.vectors_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ilwisobjectsJNI.vectors_clear(swigCPtr, this);
  }

  public void add(String x) {
    ilwisobjectsJNI.vectors_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return ilwisobjectsJNI.vectors_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    ilwisobjectsJNI.vectors_set(swigCPtr, this, i, val);
  }

}
