/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ilwisobject_test;

public class vectord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ilwisobjectsJNI.delete_vectord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }
  public vectord(double[] array) {
	this();
    for ( double i : array )
      add( i );
  }
  public vectord() {
    this(ilwisobjectsJNI.new_vectord__SWIG_0(), true);
  }

  public vectord(long n) {
    this(ilwisobjectsJNI.new_vectord__SWIG_1(n), true);
  }

  public long size() {
    return ilwisobjectsJNI.vectord_size(swigCPtr, this);
  }

  public long capacity() {
    return ilwisobjectsJNI.vectord_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ilwisobjectsJNI.vectord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ilwisobjectsJNI.vectord_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ilwisobjectsJNI.vectord_clear(swigCPtr, this);
  }

  public void add(double x) {
    ilwisobjectsJNI.vectord_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return ilwisobjectsJNI.vectord_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    ilwisobjectsJNI.vectord_set(swigCPtr, this, i, val);
  }

}
