/* 
Copyright (C) 2007 - 2015 52°North Initiative for Geospatial Open Source
Software GmbH

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as published
by the Free Software Foundation.

If the program is linked with libraries which are licensed under one of
the following licenses, the combination of the program with the linked
library is not considered a "derivative work" of the program:

      • Apache License, version 2.0
      • Apache Software License, version 1.0
      • GNU Lesser General Public License, version 3
      • Mozilla Public License, versions 1.0, 1.1 and 2.0
      • Common Development and Distribution License (CDDL), version 1.0

Therefore the distribution of the program linked with libraries licensed
under the aforementioned licenses, is permitted by the copyright holders
if the distribution is compliant with both the GNU General Public
License version 2 and the aforementioned licenses.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details. 
*/ 
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.n52.ilwis.java;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;

public class ilwisobjects {
  public static boolean _initIlwisObjects(String ilwisDir) {
    return ilwisobjectsJNI._initIlwisObjects(ilwisDir);
  }

  public static void _exitIlwisObjects() {
    ilwisobjectsJNI._exitIlwisObjects();
  }

  public static void disconnectIssueLogger() {
    ilwisobjectsJNI.disconnectIssueLogger();
  }

  public static void connectIssueLogger() {
    ilwisobjectsJNI.connectIssueLogger();
  }

  public static int getCOVERAGEATRIB() {
    return ilwisobjectsJNI.COVERAGEATRIB_get();
  }

  public static double getRUNDEF() {
    return ilwisobjectsJNI.rUNDEF_get();
  }

  public static int getIUNDEF() {
    return ilwisobjectsJNI.iUNDEF_get();
  }

  public static long getI64UNDEF() {
    return ilwisobjectsJNI.i64UNDEF_get();
  }


  public static String getsUNDEF() { return "?"; }
  public static int getshUNDEF() { return 32767; }
  public static float getFlUNDEF() { return (float)1e38; }
  private static boolean libLoaded = false;
  public final static String ilwisLocation = getIlwisLocation();
  
  public static void initIlwisObjects(String ilwisLocation) throws UnsatisfiedLinkError, SecurityException, IllegalArgumentException {
		if (!libLoaded) {
			try {
				System.loadLibrary("lib/_ilwisobjects0");
				ilwisobjects._initIlwisObjects(ilwisLocation);

				Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
					public void run() {
						ilwisobjects._exitIlwisObjects();
					}
				}));
			} finally {
				libLoaded = true;
			}
		}
	}
	
	private static String getIlwisLocation() {
		BufferedReader br = null;
		URL input = ClassLoader.getSystemResource("ilwislocation.config");
		try {
			String line;
			 
			br = new BufferedReader(new InputStreamReader( input.openStream() ));
 
			while ((line = br.readLine()) != null) {
				if (line.indexOf("=") == -1) {
					continue;
				}
				String[] lineSplit = line.split("=");
				if (lineSplit[0].equals("ilwisDir")) {
					return ( lineSplit[1] );
				}
			}
			throw new FileNotFoundException("ilwislocation.config invalid");
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (br != null)br.close();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}
		return null;
	}

  
  

}
